export const ngSlides: string[] = [
    'title',
    'problem',
    'case',
    'code',
    'template-default',
    'case_change',
    'template-change',
    'case_object_object',
    'template-object_object',
    'elm',
    'runtime_exceptions',
    'decoders',
    'elm_example',
    'ts_data_json',
    'decoder_example',
    'decode',
    'result'
];
